"""HTML element subclasses — concrete types returned by Document.create_element().

Populated into ``_ELEMENT_REGISTRY`` via ``register()`` (called by
``_document.py`` on first ``create_element()`` call).

Examples
--------
>>> from aspose_html.dom.html import register
>>> d = {}
>>> register(d)
>>> "a" in d
True
>>> "img" in d
True
"""
from aspose_html.dom.html._anchor_elements import (
    HTMLAnchorElement,
    HTMLAreaElement,
    HTMLMapElement,
)
from aspose_html.dom.html._form_elements import (
    HTMLButtonElement,
    HTMLDataListElement,
    HTMLFieldSetElement,
    HTMLFormElement,
    HTMLInputElement,
    HTMLLabelElement,
    HTMLLegendElement,
    HTMLMeterElement,
    HTMLOptGroupElement,
    HTMLOptionElement,
    HTMLOutputElement,
    HTMLProgressElement,
    HTMLSelectElement,
    HTMLTextAreaElement,
)
from aspose_html.dom.html._table_elements import (
    HTMLTableCaptionElement,
    HTMLTableCellElement,
    HTMLTableColElement,
    HTMLTableElement,
    HTMLTableRowElement,
    HTMLTableSectionElement,
)
from aspose_html.dom.html._list_elements import (
    HTMLDListElement,
    HTMLLIElement,
    HTMLOListElement,
    HTMLUListElement,
)
from aspose_html.dom.html._media_elements import (
    HTMLAudioElement,
    HTMLMediaElement,
    HTMLPictureElement,
    HTMLSourceElement,
    HTMLTrackElement,
    HTMLVideoElement,
)
from aspose_html.dom.html._metadata_elements import (
    HTMLBaseElement,
    HTMLLinkElement,
    HTMLMetaElement,
    HTMLScriptElement,
    HTMLStyleElement,
    HTMLTitleElement,
)
from aspose_html.dom.html._sectioning_elements import (
    HTMLAddressElement,
    HTMLArticleElement,
    HTMLAsideElement,
    HTMLBodyElement,
    HTMLBRElement,
    HTMLDetailsElement,
    HTMLDialogElement,
    HTMLFigCaptionElement,
    HTMLFigureElement,
    HTMLFooterElement,
    HTMLHeadElement,
    HTMLHeaderElement,
    HTMLHRElement,
    HTMLHtmlElement,
    HTMLMainElement,
    HTMLMarkElement,
    HTMLMenuElement,
    HTMLModElement,
    HTMLNavElement,
    HTMLNoScriptElement,
    HTMLPreElement,
    HTMLRubyElement,
    HTMLSectionElement,
    HTMLSmallElement,
    HTMLSummaryElement,
    HTMLTemplateElement,
    HTMLWBRElement,
)
from aspose_html.dom.html._embedded_elements import (
    HTMLCanvasElement,
    HTMLEmbedElement,
    HTMLIFrameElement,
    HTMLImageElement,
    HTMLObjectElement,
    HTMLParamElement,
)
from aspose_html.dom.html._text_elements import (
    HTMLDataElement,
    HTMLDivElement,
    HTMLHeadingElement,
    HTMLParagraphElement,
    HTMLQuoteElement,
    HTMLSpanElement,
    HTMLTimeElement,
    HTMLUnknownElement,
)
from aspose_html.dom._html_element import HTMLElement

__all__ = [
    "HTMLAddressElement",
    "HTMLAnchorElement",
    "HTMLArticleElement",
    "HTMLAsideElement",
    "HTMLFigCaptionElement",
    "HTMLFigureElement",
    "HTMLFooterElement",
    "HTMLHeaderElement",
    "HTMLMainElement",
    "HTMLMarkElement",
    "HTMLNavElement",
    "HTMLNoScriptElement",
    "HTMLRubyElement",
    "HTMLSectionElement",
    "HTMLSmallElement",
    "HTMLWBRElement",
    "HTMLButtonElement",
    "HTMLDivElement",
    "HTMLFormElement",
    "HTMLHeadingElement",
    "HTMLImageElement",
    "HTMLInputElement",
    "HTMLLinkElement",
    "HTMLMetaElement",
    "HTMLParagraphElement",
    "HTMLScriptElement",
    "HTMLSelectElement",
    "HTMLSpanElement",
    "HTMLTitleElement",
    "HTMLTableElement",
    "HTMLTableSectionElement",
    "HTMLTableRowElement",
    "HTMLTableCellElement",
    "HTMLTableCaptionElement",
    "HTMLTableColElement",
    "HTMLUListElement",
    "HTMLOListElement",
    "HTMLLIElement",
    "HTMLDListElement",
    "HTMLTextAreaElement",
    "HTMLFieldSetElement",
    "HTMLOptionElement",
    "HTMLOptGroupElement",
    "HTMLOutputElement",
    "HTMLDataListElement",
    "HTMLProgressElement",
    "HTMLMeterElement",
    "HTMLDetailsElement",
    "HTMLDialogElement",
    "HTMLTemplateElement",
    "HTMLHtmlElement",
    "HTMLHeadElement",
    "HTMLBodyElement",
    "HTMLBRElement",
    "HTMLHRElement",
    "HTMLPreElement",
    "HTMLStyleElement",
    "HTMLBaseElement",
    "HTMLLabelElement",
    "HTMLLegendElement",
    "HTMLModElement",
    "HTMLAreaElement",
    "HTMLMapElement",
    "HTMLTimeElement",
    "HTMLDataElement",
    "HTMLQuoteElement",
    "HTMLPictureElement",
    "HTMLIFrameElement",
    "HTMLEmbedElement",
    "HTMLObjectElement",
    "HTMLMediaElement",
    "HTMLVideoElement",
    "HTMLAudioElement",
    "HTMLSourceElement",
    "HTMLTrackElement",
    "HTMLCanvasElement",
    "HTMLParamElement",
    "HTMLUnknownElement",
    "HTMLSummaryElement",
    "HTMLMenuElement",
]

# Tag name → subclass mapping.  Populated into _ELEMENT_REGISTRY on first use.
_REGISTRY: dict[str, type] = {
    "address":  HTMLAddressElement,
    "a":        HTMLAnchorElement,
    "article":  HTMLArticleElement,
    "aside":    HTMLAsideElement,
    "figcaption": HTMLFigCaptionElement,
    "figure":   HTMLFigureElement,
    "footer":   HTMLFooterElement,
    "header":   HTMLHeaderElement,
    "main":     HTMLMainElement,
    "mark":     HTMLMarkElement,
    "nav":      HTMLNavElement,
    "noscript": HTMLNoScriptElement,
    "rp":       HTMLRubyElement,
    "rt":       HTMLRubyElement,
    "ruby":     HTMLRubyElement,
    "section":  HTMLSectionElement,
    "small":    HTMLSmallElement,
    "wbr":      HTMLWBRElement,
    "button":   HTMLButtonElement,
    "div":      HTMLDivElement,
    "form":     HTMLFormElement,
    "h1":       HTMLHeadingElement,
    "h2":       HTMLHeadingElement,
    "h3":       HTMLHeadingElement,
    "h4":       HTMLHeadingElement,
    "h5":       HTMLHeadingElement,
    "h6":       HTMLHeadingElement,
    "img":      HTMLImageElement,
    "input":    HTMLInputElement,
    "link":     HTMLLinkElement,
    "meta":     HTMLMetaElement,
    "p":        HTMLParagraphElement,
    "script":   HTMLScriptElement,
    "select":   HTMLSelectElement,
    "span":     HTMLSpanElement,
    "title":    HTMLTitleElement,
    "table":    HTMLTableElement,
    "thead":    HTMLTableSectionElement,
    "tbody":    HTMLTableSectionElement,
    "tfoot":    HTMLTableSectionElement,
    "tr":       HTMLTableRowElement,
    "td":       HTMLTableCellElement,
    "th":       HTMLTableCellElement,
    "caption":  HTMLTableCaptionElement,
    "col":      HTMLTableColElement,
    "colgroup": HTMLTableColElement,
    "ul":       HTMLUListElement,
    "ol":       HTMLOListElement,
    "li":       HTMLLIElement,
    "dl":       HTMLDListElement,
    "textarea":  HTMLTextAreaElement,
    "fieldset":  HTMLFieldSetElement,
    "option":    HTMLOptionElement,
    "optgroup":  HTMLOptGroupElement,
    "output":    HTMLOutputElement,
    "datalist":  HTMLDataListElement,
    "progress":  HTMLProgressElement,
    "meter":     HTMLMeterElement,
    "details":   HTMLDetailsElement,
    "dialog":    HTMLDialogElement,
    "template":  HTMLTemplateElement,
    "html":      HTMLHtmlElement,
    "head":      HTMLHeadElement,
    "body":      HTMLBodyElement,
    "br":        HTMLBRElement,
    "hr":        HTMLHRElement,
    "pre":       HTMLPreElement,
    "listing":   HTMLPreElement,
    "xmp":       HTMLPreElement,
    "style":     HTMLStyleElement,
    "base":      HTMLBaseElement,
    "label":     HTMLLabelElement,
    "legend":    HTMLLegendElement,
    "ins":       HTMLModElement,
    "del":       HTMLModElement,
    "area":      HTMLAreaElement,
    "map":       HTMLMapElement,
    "time":      HTMLTimeElement,
    "data":      HTMLDataElement,
    "blockquote": HTMLQuoteElement,
    "q":         HTMLQuoteElement,
    "picture":   HTMLPictureElement,
    "iframe":    HTMLIFrameElement,
    "embed":     HTMLEmbedElement,
    "object":    HTMLObjectElement,
    "audio":     HTMLAudioElement,
    "video":     HTMLVideoElement,
    "source":    HTMLSourceElement,
    "track":     HTMLTrackElement,
    "canvas":    HTMLCanvasElement,
    "param":     HTMLParamElement,
    "abbr":      HTMLElement,
    "b":         HTMLElement,
    "bdi":       HTMLElement,
    "bdo":       HTMLElement,
    "cite":      HTMLElement,
    "code":      HTMLElement,
    "dfn":       HTMLElement,
    "em":        HTMLElement,
    "i":         HTMLElement,
    "kbd":       HTMLElement,
    "s":         HTMLElement,
    "samp":      HTMLElement,
    "slot":      HTMLElement,
    "strong":    HTMLElement,
    "sub":       HTMLElement,
    "sup":       HTMLElement,
    "u":         HTMLElement,
    "var":       HTMLElement,
    "summary":   HTMLSummaryElement,
    "menu":      HTMLMenuElement,
}


def register(target: dict[str, type]) -> None:
    """Populate *target* with the tag-name → subclass mapping.

    Called once by ``Document._try_load_html_registry()`` on first
    ``create_element()`` call.  Modifies *target* in place.

    Examples
    --------
    >>> from aspose_html.dom.html import register
    >>> d = {}
    >>> register(d)
    >>> "a" in d
    True
    >>> "img" in d
    True
    >>> "select" in d
    True
    """
    target.update(_REGISTRY)
